name: Collect Marketplace Data

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    environment: API_KEY
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install python-dotenv

      - name: Run data collection script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python collect_marketplace_data.py
          ls -la exported_csvs/

      - name: Upload CSV files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: healthcare-data
          path: |
            exported_csvs/*.csv
            marketplace.db
            healthcare_plans.json
          retention-days: 5

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update marketplace data [skip ci]"
          branch: main
          add_options: '--all'
          file_pattern: |
            exported_csvs/*.csv
            marketplace.db
            healthcare_plans.json
      
      - name: Upload database to artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: database-backup
          path: marketplace.db
          retention-days: 30
