name: Collect Marketplace Data

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:

jobs:
  collect:
    runs-on: ubuntu-latest
    environment: API_KEY
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run data collection script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python collect_marketplace_data.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update marketplace data"
          branch: main
